[project]
name = "core-vault"
authors = ["CoreVault Team"]
description = "A secure, decentralized vault management system on Stacks blockchain"
telemetry = false
requirements = []
[contracts.vault-core]
path = "contracts/vault-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
